---
title: "R packages"
description: |
  We maintain and are key contributors to several R packages
---
Here we list our main contributions. 

We also contribute to many other R packages, but our contributions are not as crucial or the projects are small and experiemental.
For more details, you can check our GitHub pages:

- [<i class='fa fa-github'></i> Alexandre Courtiol](https://github.com/courtiol)
- [<i class='fa fa-github'></i> Liam Bailey](https://github.com/LiamDBailey)

## Open source

### For natural scientists {#main_packages}

- [climwin](https://cran.r-project.org/web/packages/climwin/index.html) to detect and visualise periods of climate sensitivity (climate windows) for a given biological response. Created and maintained by Liam.
- [IsoriX](https://cran.r-project.org/web/packages/IsoriX/index.html) to build isoscapes using mixed models and infer the geographic origin of organisms based on their isotopic ratios. Created and maintained by Alex.
- [torpor](https://github.com/vullioud/torpor) to fit thermoregulatory curves in heterothermic endotherm species, while assigning metabolic rates to the correct physiological state. Created by Colin, while with us.
- [camtrapR](https://cran.r-project.org/web/packages/camtrapR/index.html) to manage camera trap photographs in wildlife studies. We helped its maintainer -- Jürgen Niedballa -- to set it up while he was still a PhD student.

### For all data scientists

- [spaMM](https://cran.r-project.org/web/packages/spaMM/index.html) to efficiently fit linear models of varying complexity, including mixed models with spatial autocorrelation. We contribute to its development mostly by using this package a lot, debugging it and suggesting new features. Maintained by one very close collaborator ([François Rousset](https://kimura.univ-montp2.fr/~rousset)).
- [ABMR6](https://github.com/LiamDBailey/ABMR6) an example of how to implement individual-based simulation using R6. Created by Alex, maintained by Liam.
- [timevarcorr](https://github.com/courtiol/timevarcorr) to estimate time varying correlation coefficients using non-parametric kernel smoothing. Created and maintained by Alex.

## Private (for now)

- [hyenaR](https://github.com/hyenaproject/hyenaR) to manage most of the data generated by the [hyena project](https://hyena-project.com). Created and maintained by Liam and Alex.
- [HyenaPopmod ](https://github.com/hyenaproject/HyenaPopmod) to perform individual-based simulations mimicking the hyenas followed by the [hyena project](https://hyena-project.com). Created and maintained by Liam.

These packages will become open whenever we will judge them ready for others to use.
